### ISSUE TITLE
Device Types

### ISSUE THREAD

**Issue by cnn123666** [ShadyNawara/WLEDAuraSync#1]
Hello, I would like to ask whether all asus devices are controlled
Because I noticed this line aurasDK. List (0)
How do I limit only the motherboard (M/B) and the LED strip to be controlled in M/B, while the others are not

**Comment by ShadyNawara** [comment]
Are your trying to turn the other devices off? Or have them controlled by another software at the same time?

**Comment by cnn123666** [comment]
Sorry, my expression is wrong, I only want to control the motherboard (ARGB) and memory, what should I do

**Comment by ShadyNawara** [comment]
After running the wledaurasync.exe 
you should see a window similar to this

![image](https://user-images.githubusercontent.com/981568/136678666-12ab5d9a-b247-43a2-8fd0-3b0bcfe73b00.png)

in my case the first 3 devices were my motherboard and memory (2 memory sticks then the motherboard)
they had a total of 24 leds so you can go to the wled interface and set your led count to 24.
that should technically only control the memory and motherboard.

if there are devices in between that you dont want to control, you can create segments in the wled UI
for example if i want to control only the 1st device (one memory stick) and 3rd device(motherboard) in the list
you would still set the total led count to 24 and then create 3 segments with 8 leds each which would give you individual control over each device.

let me know if that helps or if you were trying to do something different.

**Comment by cnn123666** [comment]
I ran into a very strange BUG
Running ‘.apply ()’  is very time consuming
So I want to run in multiple threads, but as soon as I start the thread, it crashes

**Comment by ShadyNawara** [comment]
I dont think the Aura SDK is thread safe. how much fps are you getting? also try out my latest version, it only calls .apply when leds actually need to change.

**Comment by cnn123666** [comment]
I set it to 33 milliseconds, run it once. Apply()
There may be 30 FPS
I'm a window program   Real-time preview of leds 
![微信截图_20211109125143](https://user-images.githubusercontent.com/52467395/140865067-acb25551-7f57-45d7-bfbf-298a3e473b57.png)
so I have to thread refresh,.apply ()

Will upload the code to Github at a later date

**Comment by ShadyNawara** [comment]
looks cool. you can still run .apply() on a different thread just make sure that the thread calling .apply is the same one acquiring control
`		
// Create SDK instance
		AuraServiceLib::IAuraSdkPtr sdk = nullptr;
		hr = sdk.CreateInstance(__uuidof(AuraServiceLib::AuraSdk), nullptr, CLSCTX_INPROC_SERVER);
		if (SUCCEEDED(hr))
		{
			// Acquire control
			sdk->SwitchMode();
`

**Comment by cnn123666** [comment]
My idea is to use ICUE to control WLED and Aura

**Comment by cnn123666** [comment]
WLED built-in lights are not as cool as ICUE

**Comment by ShadyNawara** [comment]
good luck, I would love to see the result when you are done.
